name = "Sum_of_Powers"
uuid = "80c193fa-e468-4de1-bbbd-209fc801bb16"
authors = ["Christopher Stook <chris@chrisstook.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
