name = "Sum_of_Powers"
uuid = "80c193fa-e468-4de1-bbbd-209fc801bb16"
authors = ["Christopher Stook <chris@chrisstook.com>"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
